import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from 'next-auth/react';
import {auth} from "@/app/auth";
// import GlobalState from "@/[action]/GlobalState";
// import {connection} from "next/server";
import { Provider } from "jotai";
import {GraphQLProvider} from "@/auth/graphql-component";
// import PrintUsed from "@/common/PrintUsed";
// import AuthStatus from "@/auth/auth-status";
import { ThemeProvider } from 'next-themes'
import { Toaster } from "sonner"
import "@/styles/print-styles.css" // 导入打印样式
import "./globals.css";
import {PrintSettingsProvider} from "@/contexts/print-settings-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//上面的层次的layout放入文字布局内容需要考虑报告的打印影响。
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await auth();
  return (
      <html suppressHydrationWarning>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased @container`}
      >
      <ThemeProvider>
        <PrintSettingsProvider>
          {/*<PrintUsed/>*/}
          <SessionProvider session={session}>
              <Provider>
                  <GraphQLProvider>
                      {children}
                      <Toaster richColors position="top-right" />
                  </GraphQLProvider>
              </Provider>

              {/*<GlobalState>*/}
              {/*    <AppStateProvider>*/}
              {/*        <SwrConfigClient>*/}

              {/*            {children}*/}

              {/*            <Suspense fallback={<div className="text-yellow-500">Loading56data...</div>}>*/}
              {/*                <MainContent/>*/}
              {/*            </Suspense>*/}
              {/*        </SwrConfigClient>*/}
              {/*    </AppStateProvider>*/}
              {/*</GlobalState>*/}
              {/*<ToastContainer/>*/}

          </SessionProvider>
        </PrintSettingsProvider>
      </ThemeProvider>
      </body>
      </html>
  );
}


/*
        <html suppressHydrationWarning>
        <head>
            <style>
                {`
            body {
                padding: 0;
                margin: 0;
            }
            @page portraitPg {
                size: a4 portrait;
                @top-middle {
                    content: "Table of ntentsff3";
                }
            }
            @page landscapePg {
                size: a4 landscape;
                @top-middle {
                    content: "Chapte r5sdfg";
                }
            }
            @media print {
                .WideChapter {
                    page: landscapePg;
                }
                .UsualChapter {
                    page: portraitPg;
                }
                nextjs-portal,next-route-announcer {
                    display: none;
                }
            }
            `}
            </style>
        </head>
        <body>
* */