import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from 'next-auth/react';
import {auth} from "@/app/auth";
// import GlobalState from "@/[action]/GlobalState";
// import {connection} from "next/server";
import { Provider } from "jotai";
import {GraphQLProvider} from "@/auth/graphql-component";
import PrintUsed from "@/common/PrintUsed";
import AuthStatus from "@/auth/auth-status";
import { ThemeProvider } from 'next-themes'

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await auth();
  return (
      <html suppressHydrationWarning>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider>
          {/*<PrintUsed/>*/}
          <SessionProvider session={session}>
              <AuthStatus/>
              <Provider>
                  <GraphQLProvider>
                      {children}
                  </GraphQLProvider>
              </Provider>

              {/*<GlobalState>*/}
              {/*    <AppStateProvider>*/}
              {/*        <SwrConfigClient>*/}

              {/*            {children}*/}

              {/*            <Suspense fallback={<div className="text-yellow-500">Loading56data...</div>}>*/}
              {/*                <MainContent/>*/}
              {/*            </Suspense>*/}
              {/*        </SwrConfigClient>*/}
              {/*    </AppStateProvider>*/}
              {/*</GlobalState>*/}
              {/*<ToastContainer/>*/}

          </SessionProvider>
      </ThemeProvider>
      </body>
      </html>
  );
}


/*
        <html suppressHydrationWarning>
        <head>
            <style>
                {`
            body {
                padding: 0;
                margin: 0;
            }
            @page portraitPg {
                size: a4 portrait;
                @top-middle {
                    content: "Table of ntentsff3";
                }
            }
            @page landscapePg {
                size: a4 landscape;
                @top-middle {
                    content: "Chapte r5sdfg";
                }
            }
            @media print {
                .WideChapter {
                    page: landscapePg;
                }
                .UsualChapter {
                    page: portraitPg;
                }
                nextjs-portal,next-route-announcer {
                    display: none;
                }
            }
            `}
            </style>
        </head>
        <body>
* */