POST https://192.168.171.3:8673/uploadTUS/
Tus-Resumable: 1.0.0
Upload-Length: 1024
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZXJ6aGFuZyIsImlhdCI6MTc2MjMxMjI3NywiZGV2aWNlSWQiOiJlMnM4dGx5IiwiZXhwIjoxNzYyMzE0Mjc3fQ.wrXNrENlhSH3o_3BXlLkQxEXCuZqO3Tt14cBAYYQMofFjt4greMWdXxekaf9uuSJiDfWRBSGXuvTABc3Vo6S0A
Connection: close

###


# curl -X POST
#  https://192.168.171.3:8673/uploadTUS/
#  -H "Accept: application/json"
#  -H "Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZXJ6aGFuZyIsImlhdCI6MTc2MjMxMjI3NywiZGV2aWNlSWQiOiJlMnM4dGx5IiwiZXhwIjoxNzYyMzE0Mjc3fQ.wrXNrENlhSH3o_3BXlLkQxEXCuZqO3Tt14cBAYYQMofFjt4greMWdXxekaf9uuSJiDfWRBSGXuvTABcVo6S0A"
#  --http1.1
#  -k
POST https://192.168.171.3:8673/uploadTUS/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZXJ6aGFuZyIsImlhdCI6MTc2MjMxMjI3NywiZGV2aWNlSWQiOiJlMnM4dGx5IiwiZXhwIjoxNzYyMzE0Mjc3fQ.wrXNrENlhSH3o_3BXlLkQxEXCuZqO3Tt14cBAYYQMofFjt4greMWdXxekaf9uuSJiDfWRBSGXuvTABc3Vo6S0A

###

# curl -X POST
#  https://192.168.171.3:8673/uploadTUS/
#  -H "Accept: application/json"
#  -H "Authorization: Bearer your_token_here"
#  -H "Tus-Resumable: 1.0.0"
#  -H "Upload-Length: 1024"
#  --http1.1
#  -k -v
POST https://192.168.171.3:8673/uploadTUS/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZXJ6aGFuZyIsImlhdCI6MTc2MjMxNDM3MywiZGV2aWNlSWQiOiJlMnM4dGx5IiwiZXhwIjoxNzYyMzE2MzczfQ.hFfWyu7WBsyggnM59KfuPm9ORom3xohNAp3IZ2WyHicRfLXHmRhU0Ifp7MOJS9PgIIdo2c50Z1b5pEzeaiBmsA
Tus-Resumable: 1.0.0
Upload-Length: 1024

###