###仅做2个文件合并，不牵涉到网页转换的
POST https://192.168.171.3:8673/api/pdf
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "merge": true,
  "name": "合并2个文件原始的办法",
  "lay": {
  },
  "files": [
    {
      "url": "rep-1stp.pdf"
    },
    {
      "url": "横页脚的VS2.pdf"
    }
  ]
}
###
POST http://localhost:9389/api/pageSeq
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "ids": ["BoilerDiagram",
    "Explanatory"
  ]
}
###本地测试的2w
POST http://192.168.0.100:9389/api/pageSeq
Accept: application/json
Content-Type: application/json; charset=utf-8
Authorization: Basic YWRtaW46Q2VyNmpzJGt3OWUwV2E=

{
  "merge": true,
  "name": "报告e9",
  "lay": {
  },
  "files": [
    {
      "url": "http://192.168.171.3:3765/rep/KQcbgDF9RO21DsI92H3tTVJlcG9ydA/POWER_AJ/1?print=1",
      "out": "报告ert459"
    }
  ]
}
