import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from 'next-auth/react';
import {auth} from "@/app/auth";
// import {connection} from "next/server";
import { Provider, atom, useAtom } from "jotai";
import {GraphQLProvider} from "@/auth/graphql-component";
import { ThemeProvider } from 'next-themes'
import { Toaster } from "sonner"
import "@/styles/print-styles.css" // 导入打印样式
import "./globals.css";
import {PrintSettingsProvider} from "@/contexts/print-settings-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//上面的层次的layout放入文字布局内容需要考虑报告的打印影响。
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await auth();
  return (
      <html suppressHydrationWarning>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased @container`}
      >
      <ThemeProvider>
        <PrintSettingsProvider>
          <SessionProvider session={session}>
              <Provider>
                  <GraphQLProvider>
                      {children}
                      <Toaster richColors position="top-right" />
                  </GraphQLProvider>
              </Provider>
          </SessionProvider>
        </PrintSettingsProvider>
      </ThemeProvider>
      </body>
      </html>
  );
}
