import type { Metadata } from "next";
import { SessionProvider } from 'next-auth/react';
import {auth} from "@/app/auth";
// import {connection} from "next/server";
import { Provider, atom, useAtom } from "jotai";
import {GraphQLProvider} from "@/auth/graphql-component";
import { ThemeProvider } from 'next-themes'
import { Toaster } from "sonner"
import "@/styles/print-styles.css" // 导入打印样式
import {PrintSettingsProvider} from "@/contexts/print-settings-context";
import type React from "react"
import { notoSans, notoSerif } from '@/styles/fonts';
import "./globals.css"
import {SiteMainbar} from "@/components/site-mainbar";
import HeaderWrapper from "@/component/header-wrapper"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const session = await auth();
    return (
        <html suppressHydrationWarning lang="zh-CN">
        <body
            className={`${notoSans.variable} ${notoSerif.variable} antialiased
             bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 @container
            `}
        >
        <ThemeProvider>
            <PrintSettingsProvider>
                <SessionProvider session={session}>
                    <Provider>
                        <GraphQLProvider>
                            <HeaderWrapper />
                            {children}
                            <Toaster richColors position="top-right" />
                        </GraphQLProvider>
                    </Provider>
                </SessionProvider>
            </PrintSettingsProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
