import type { Metadata } from "next";
import { SessionProvider } from 'next-auth/react';
import {auth} from "@/app/auth";
// import {connection} from "next/server";
import { Provider, atom, useAtom } from "jotai";
import {GraphQLProvider} from "@/auth/graphql-component";
import { ThemeProvider } from 'next-themes'
import { Toaster } from "sonner"
import "@/styles/print-styles.css" // 导入打印样式
import {PrintSettingsProvider} from "@/contexts/print-settings-context";
import type React from "react"
import { Inter, Noto_Sans_SC, Noto_Serif_SC } from "next/font/google"
import "./globals.css"

// 配置英文字体
const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
})

// 配置中文无衬线字体
const notoSansSC = Noto_Sans_SC({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700", "900"],
    display: "swap",
    variable: "--font-noto-sans-sc",
})

// 配置中文衬线字体
const notoSerifSC = Noto_Serif_SC({
    subsets: ["latin"],
    weight: ["400", "500", "700", "900"],
    display: "swap",
    variable: "--font-noto-serif-sc",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

//上面的层次的layout放入文字布局内容需要考虑报告的打印影响。
export default async function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    const session = await auth();
    return (
        <html suppressHydrationWarning
            lang="zh-CN" className={`${inter.variable} ${notoSansSC.variable} ${notoSerifSC.variable} antialiased`}>
        <head>
            {/* 预加载关键字体 */}
            <link
                rel="preload"
                href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300;400;500;700;900&display=swap"
                as="style"
            />
            <link
                rel="preload"
                href="https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;500;700;900&display=swap"
                as="style"
            />
        </head>
        <body className="font-sans bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 @container">
        <ThemeProvider>
            <PrintSettingsProvider>
                <SessionProvider session={session}>
                    <Provider>
                        <GraphQLProvider>
                            {children}
                            <Toaster richColors position="top-right" />
                        </GraphQLProvider>
                    </Provider>
                </SessionProvider>
            </PrintSettingsProvider>
        </ThemeProvider>
        </body>
        </html>
    )
}
